platform:ios, '7.0'
pod 'MYBlurIntroductionView', '~> 1.0.3'
pod 'AFNetworking', '~> 2.6.0'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'ZYQAssetPickerController', '~> 1.0.0'
pod 'FMDB', '~> 2.5'
pod 'MJRefresh', '~> 2.4.12'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'LCActionSheet', '~> 1.0.6'
